---
abstract: 'Tell Log::Any where to send its logs'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Any-Adapter
no_index:
  file:
    - lib/Log/Any/Adapter/FileScreenBase.pm
    - lib/Log/Any/Adapter/Test/Memory.pm
    - lib/Log/Any/Adapter/Util.pm
requires:
  Capture::Tiny: 0
  Carp: 0
  Devel::GlobalDestruction: 0
  Guard: 0
  Log::Any: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Log-Any-Adapter
  repository: git://github.com/jonswar/perl-log-any-adapter.git
version: 0.08
